core/Network/TLS/Handshake/Process.hs, core/Network/TLS/Handshake/Server.hs, core/Network/TLS/Parameters.hs, core/Tests/Tests.hs
37cb71ba3f49310fc27f234ed1f643486b9f6700 was accidentally cherry-picked. I should have written this comment when I created the patch.
=> adding comments about secure renegotiation.

core/Network/TLS/Handshake/Server.hs, core/Network/TLS/Parameters.hs, core/Network/TLS/Struct.hs, core/Network/TLS/Types.hs
This implements fallback SCSV in the server side. Tested by https://www.ssllabs.com/ssltest/.
=> Fallback SCSV

core/Network/TLS.hs, core/Network/TLS/Backend.hs, core/Network/TLS/Context.hs, core/Network/TLS/Extension.hs, core/Network/TLS/Parameters.hs, core/tls.cabal
As stated in the commits, this pull request should have no effect when the `tls` library is built with its default flags. Instead, it modifies `tls` to be flexible with regard to which network stack(s) it is combined with by providing a `network` flag and a `hans` flag. Again, by default `network` is set and `hans` is unset, which leads to the old default behavior.
Note that these flags are not alternatives to each other; both may be set to true and both may be set to false, depending on the underlying user's needs.
=> Add HaNS as an additional / alternative underlying network stack.

core/Network/TLS.hs, core/Network/TLS/Core.hs, core/Network/TLS/Handshake/Server.hs, core/Network/TLS/Parameters.hs, core/Network/TLS/State.hs
This attempts to address issue #103. The first commit allows the server credentials used during the handshake to depend on the SNI information provided by the client. This is necessary to support the implementation of transparrent proxies or virtual hosts where different credentials should be used for different domains and credentials may need to be created on demand if the full set of supported domains is not known in advance.
The second commit provides the getClientSNI function alluded to in the original issue, allowing the server to query the host that the client specified after the handshake has completed.
=> Support SNI on the server side (Issue #103)

debug/src/RetrieveCertificate.hs
tls-retreivecertificate's help message says that it shoud use port 443
as default port if unpsecified as a command-line argument.
=> tls-retreivecertificate: use 443 as port if unspecified

core/Network/TLS/Parameters.hs, core/Network/TLS/Sending.hs
There are cases when another protocol is encapsulated to TLS and that protocol's implementation disconnects when empty unexpected packet gets received.
This pull request adds an option to avoid sending that empty packet when explicitly requested by user even if that compromises security.
=> Allow users to disable sending an empty packet for TLS <= 1.0 with CBC ciphers

core/Benchmarks/Benchmarks.hs, core/tls.cabal
The `bench-tls` build was failing due to an unlisted dependency on `tasty-quickcheck`, and due to breaking changes in `criterion` 1.0.0.
=> Fix benchmarks build

core/Network/TLS/Handshake/Signature.hs
Fixes getting "unimplemented RSA signature hash type: HashSHA384" when connecting as a client to Go TLS servers.
=> Support SHA-384 with RSA

core/tls.cabal
Without this `cabal install tls` fails on GHC < 7.6. I've [applied revisions](https://hackage.haskell.org/package/tls-1.3.4/revisions/) so a new release of tls isn't necessary.
```
Network/TLS/State.hs:96:52:
No instance for (Applicative
(Control.Monad.Error.ErrorT TLSError (State TLSState)))
arising from the 'deriving' clause of a data type declaration
Possible fix:
add an instance declaration for
(Applicative
(Control.Monad.Error.ErrorT TLSError (State TLSState)))
or use a standalone 'deriving instance' declaration,
so you can specify the instance context yourself
When deriving the instance for (Applicative TLSSt)
```
=> Require mtl >= 2 due to compilation failure on 1.*

.travis.yml, core/Network/TLS/Handshake/Common.hs, core/Network/TLS/Handshake/Signature.hs, core/Network/TLS/Parameters.hs, core/tls.cabal, debug/src/SimpleClient.hs, debug/src/SimpleServer.hs, debug/src/Stunnel.hs
See https://github.com/vincenthz/hs-tls/issues/143
In particular:
>Here are the major changes I made (in no particular order):
>
>1. Fixed the `mempty` import for GHC versions lower than 7.10.
>2. Made `tls` to not be a dependency of itself. This was making the build fail when it should pass, due to the source on Hackage (which we are trying to update) failing to build.
>3. Installed the cloned `tls` in the local `cabal` as part of the Travis build. This ensures that `tls-debug` will use the current code, rather than trying to download the package from Hackage.
>4. Made (the locally installed) `tls` a dependency of its own test suite and benchmark.
>5. Made the travis build only install the necessary GHC and cabal-install versions.
>6. Changed the lower-bound of `base` to coincide with …
=> Get tls working again on GHC < 7.10, and fix the Travis build

core/Network/TLS/Context.hs, core/Network/TLS/Context/Internal.hs, core/Network/TLS/Handshake/Client.hs, core/Network/TLS/Handshake/Server.hs
This allows to create list of supported ciphers after we have answer from SNI hook.
Technically SNI is always called so if our callback supports `Nothing`  we cover all cases and, really not need the main certificate.
It is possible that additional credentials will support different ciphers than the main one so we need to retest it after we know which ciphers we actually have.
=> Sni late checks

core/Network/TLS/Cipher.hs, core/Network/TLS/Context.hs, core/Network/TLS/Extension.hs, core/Network/TLS/Extra/Cipher.hs, core/Network/TLS/Handshake/Key.hs, core/Network/TLS/Handshake/Server.hs, core/Network/TLS/Handshake/Signature.hs, core/Network/TLS/Handshake/State.hs, core/Network/TLS/MAC.hs, core/Network/TLS/Packet.hs, core/Network/TLS/Parameters.hs, core/Tests/Connection.hs
This PR implements support for TLS12 ciphersuites with SHA384 (or other, though none yet in use) PRFs.
It also adds some new cipher code points that fill existing gaps.
With this done ECDSA signature algorithms are enabled, and secp384r1 is added to the supported curves.  See individual commit logs for more detail.
=> Enable sha384 ciphers

core/Network/TLS/Cipher.hs, core/Network/TLS/Extra/Cipher.hs
When I'm implement TLS 1.3, I sometime suffer from cyclic imports. This is because the current imports are unnecessarily large. This patch reduces this issue.
=> Making import minimum.

core/Tests/Connection.hs
These values make test much slower.
Since 128 bit security is good enough to around 2050,
testing up to ffdhe3072 (125 bit security) is sufficient.
=> removing ffdhe4096, ffdhe6144 and ffdhe8192 from tests.

debug/src/SimpleClient.hs
A file lock error happens if an output file is specified AND
a session is resumed. This patch closes the output file
so that the resumed session can re-open it safely.
=> closing the output file.

debug/src/SimpleClient.hs, debug/src/SimpleServer.hs, debug/src/Stunnel.hs
The reason for local cipher suites in tls-debug utilities looks historical.
To get accurate diagnostics from the utilities it is important keep the ciphers identical to what is commonly used.
This PR replaces the local lists with the usual ciphers from `Network.TLS.Extra.Cipher`:
* `ciphersuite_all` in clients (this is what is used in `connection` and dependent packages)
* `ciphersuite_default` in servers (a little more secure)
=> tls-debug cipher suites

.travis.yml, core/Network/TLS/Extra/Cipher.hs, core/Network/TLS/Handshake/Signature.hs, core/tls.cabal
I see two explanations for TestClient failures in Travis builds:
* the default hash algorithm for ECDSA should be SHA-1 (just like for DSA)
as described in RFC 4492 § 5.4
* what looks like a copy/paste mistake in the definition of two ECDSA ciphers
=> Fix ECDSA with TLS 1.0 / TLS 1.1

core/tls.cabal
=> requiring network >= 2.4.0.0.

core/Network/TLS/Handshake/Signature.hs, core/Tests/Connection.hs, core/Tests/Tests.hs
This is a fix for the scenario with client certificate reported in #111.
Steps to reproduce:
```shell
cd /tmp
openssl req -x509 -new -subj /CN=localhost -nodes -text -out cert.pem
openssl s_server -key /tmp/privkey.pem -cert /tmp/cert.pem -www \
-verify 1 -CAfile /tmp/cert.pem
tls-simpleclient --tls11 --no-validation --use-cipher=47 \
--client-cert=/tmp/cert.pem:/tmp/privkey.pem \
localhost 4433
```
=> RSA signature in CertificateVerify with TLS < 1.2

core/Network/TLS/Handshake/Process.hs, debug/src/SimpleServer.hs
This is a fix for #161.
The handshake behaviour is slightly modified because the implementation will now accept to start a second handshake replacing a first handshake that is not finished yet. I don’t think this can cause any harm, especially with secure renegotiations. But if required it should also be possible to use more complex logic or add new state to discriminate between finished and on-going handshake cases.
=> Restore ability to renegotiate

core/Network/TLS/Credentials.hs, core/Network/TLS/Handshake/Client.hs, core/Network/TLS/Handshake/Server.hs, core/Network/TLS/Handshake/Signature.hs, core/Network/TLS/Packet.hs, core/Network/TLS/Parameters.hs, core/Tests/Connection.hs, core/Tests/Tests.hs
This extends #177 so that the "signature_algorithms" extension impacts cipher selection as discussed in #191.
I added a new test case specific to TLS 1.2 where handshake can either succeed or fail depending on client and server `supportedHashSignatures`. This could be further extended to test more TLS 1.2 extensions like "supported_groups" when we implement it.
I also added code for DSA certificates, so that the QuickCheck properties can test more combinations.
=> Selecting a cipher based on "signature_algorithms"

core/tls.cabal
This affects GHC 7.4 and earlier.
The error is
```
Network/TLS/Handshake/Client.hs:275:13:
Warning: Pattern match(es) are overlapped
In a case alternative: _ -> ...
[47 of 52] Compiling Network.TLS.Handshake.Server ( Network/TLS/Handshake/Server.hs, /tmp/matrix-worker/1489475638/dist-newstyle/build/x86_64-linux/ghc-7.4.2/tls-1.3.10/build/Network/TLS/Handshake/Server.o )
Network/TLS/Handshake/Server.hs:37:18:
Module `Data.Ord' does not export `Down(..)'
```
The other alternative is to use CPP to add
```haskell
-- | The 'Down' type allows you to reverse sort order conveniently.  A value of type
-- @'Down' a@ contains a value of type @a@ (represented as @'Down' a@).
-- If @a@ has an @'Ord'@ instance associated with it then comparing two
-- values thus wrapped will give you the opposite of …
```
=> Build fails for base < 4.6

.travis.yml
@alanz kindly pointed out that we should use 8.0.2 instead of 8.0.1 on Travis.
=> using GHC 8.0.2 on travis.

test-scripts/openssl-client.c, test-scripts/openssl-server.c
About warnings: format placeholders from C99 should fix the message visible in the Travis build.
=> Use platform-independent printf placeholders

core/Network/TLS/Context.hs, core/Network/TLS/Credentials.hs, core/Network/TLS/Crypto.hs, core/Network/TLS/Crypto/Types.hs, core/Network/TLS/Handshake/Client.hs, core/Network/TLS/Handshake/Key.hs, core/Network/TLS/Handshake/Server.hs, core/Network/TLS/Handshake/Signature.hs, core/Network/TLS/Struct.hs, core/Tests/Tests.hs, core/tls.cabal
This implements #206.
Since TLS 1.3 flattens the structure of (Hash, Signature) and Hash 0x08 is a magic word for TLS 1.3, implementation is not straightforward and a little bit tricky.
=> Supporting RSAPSS defined in TLS 1.3

core/Tests/Connection.hs, core/Tests/Tests.hs
Since ECDHE would be an only common cipher, client/server groups
should always have a common group.
prop_handshake_initiate_tls12 is removed since no common hash-signature
does not always cause a handshake error. Rather, supportedHashSignatures
is specified with available hash-signatures shuffled.
=> using ciphersuite_strong for tests.

core/Network/TLS/IO.hs
Probably just cruft left over from when this code was `MonadIO m` instead of `IO`.
=> Network.TLS.IO: Remove un-needed liftIO

core/Network/TLS/Extra/Cipher.hs, debug/src/Common.hs
This is the first step for #153.
=> adding the warnig and deprecated pragmas for ciphersuite.

core/Benchmarks/Benchmarks.hs, core/tls.cabal, debug/tls-debug.cabal, test-scripts/tls-test.cabal
- use at least cryptonite-0.23 to prevent any segmentation fault with P256
- fix benchmark compilation
I thought about compiling benchmarks in the Travis script but stepped back because of criterion many dependencies.
=> Follow-up to #205 and #216

core/Network/TLS.hs, core/Network/TLS/Context/Internal.hs, core/Network/TLS/Credentials.hs, core/Network/TLS/Crypto/IES.hs, core/Network/TLS/Handshake/Common.hs, core/Network/TLS/Handshake/Signature.hs, core/Network/TLS/Handshake/State.hs, core/Network/TLS/IO.hs, core/Network/TLS/Imports.hs, core/Network/TLS/MAC.hs, core/Network/TLS/Packet.hs, core/Network/TLS/Parameters.hs, core/Network/TLS/Record/Disengage.hs, core/Network/TLS/Record/State.hs, core/Network/TLS/Record/Types.hs, core/Network/TLS/State.hs, core/Network/TLS/Struct.hs, core/Network/TLS/Util.hs, core/Network/TLS/Wire.hs
`Bytes` was a type alias for `ByteString`. The `Bytes` type is kept
because it is exposed in the API.
Have built http-client-tls and warp-tls from Hackage with this
version of tls and zero changes were needed in those packages.
Related to #229 . I have no problem whatsoever moving from `Bytes`/`ByteString` to `ByteArray` but while `Bytes` and `ByteString` are the same, `Bytes` should be replaced with `ByteString` if it can be done without breaking the API (and it can).
=> Change Bytes to ByteString

core/Tests/Ciphers.hs, core/Tests/Connection.hs, debug/src/Common.hs, debug/src/SimpleServer.hs, debug/src/Stunnel.hs
Need to disable this warning so we can still test deprecated
functionality but also not get a warning.
=> Tests/Ciphers.hs: Disable deprecation warning

debug/src/CheckCiphers.hs, debug/src/RetrieveCertificate.hs, debug/src/SimpleClient.hs, debug/src/SimpleServer.hs, debug/src/Stunnel.hs
Session resumption between `tls-simpleclient` and `tls-simpleserver` sometimes fails for some reasons. This PR include:
- Setting reuseaddr to server sockets
- Ignoring an error of `bye` in the client side
- Waiting a bit to ensure that the server can prepare the next socket
- Preventing warnings
=> Make session resumption successful

core/Network/TLS/Context.hs, core/Network/TLS/Context/Internal.hs, core/Network/TLS/Credentials.hs, core/Network/TLS/Crypto.hs, core/Network/TLS/Handshake/Client.hs, core/Network/TLS/Handshake/Server.hs, core/Network/TLS/Handshake/Signature.hs, core/Network/TLS/Parameters.hs, core/Network/TLS/Struct.hs, core/Tests/Certificate.hs, core/Tests/Connection.hs, core/Tests/Tests.hs, core/tls.cabal
This adds behavior described in #195, with a rework of how cipher/credential code is organized.
I was reluctant to create impacts for something non essential like #195 but see now that supporting EdDSA in the future will require filtering credentials (instead of ciphers like we did before). 
On a diagram we need to go from this:
```
Pub/Priv Key Type <-- Key Exchange Type <-- HashAndSignatureAlg
(credential)      <-- (cipher)          <-- (supported exts)
```
to this:
```
Key Exchange Type <--> Pub/Priv Key Type <-- HashAndSignatureAlg
(cipher)          <--> (credential)      <-- (supported exts)
```
This is because the relation between key exchange and certificate will become n..n:
| Key Exchange | Public/Private Key |
|--------------|--------------------|
| DHE_RSA      | RSA …
=> Improve selection of server certificate and use "signature_algorithms" extension

core/Network/TLS/Core.hs, core/Network/TLS/Handshake.hs
In snoyberg/http-client#273 was reported a new case where tls external API throws TLSError directly instead of wrapping the value in TLSException (failure seen when connecting to https://paste.debian.net with tls-1.3.9).
This PR applies the same error handling when renegotiation handshake is triggered locally or remotely.
=> Wrap renegotiation failures with HandshakeFailed

debug/tls-debug.cabal
Releasing tls-debug would be good too as we've added features and updated the cipher lists.
=> Allow tls-1.4.0 in tls-debug

core/Network/TLS/Handshake.hs
Here catching only IOException looks preferable as the goal is simply to ignore.
=> Handle TCP reset during handshake

core/Network/TLS/Credentials.hs, core/Network/TLS/Extension.hs, core/Network/TLS/Handshake/Client.hs, core/Network/TLS/Handshake/Server.hs, core/Network/TLS/Imports.hs, core/Network/TLS/Packet.hs
I always misunderstand that `fromJust` is from `Data.Maybe` and am confused. To avoid this, renaming the original `fromJust` might be a good idea. If we do this, we can export `Data.Maybe` from `Imports` safely.
=> renaming fromJust and exporting Data.Maybe from Imports.

core/Network/TLS.hs, core/Network/TLS/Crypto.hs, core/Network/TLS/Crypto/DH.hs, core/Network/TLS/Crypto/IES.hs, core/Network/TLS/Crypto/Types.hs, core/Network/TLS/Handshake/Client.hs, core/Network/TLS/Handshake/Key.hs, core/Network/TLS/Handshake/Process.hs, core/Network/TLS/Handshake/Server.hs, core/Network/TLS/Parameters.hs, core/Tests/Connection.hs, core/Tests/Tests.hs
After ECDH this is to improve validation in DH key exchange:
- support for named FFDHE groups (RFC 7919), in addition to custom groups we have today
- minimal validation of DH parameters (but which is enough when using named FFDHE groups)
- optional client callback to implement policy about custom groups
When DHE params match a named group, internally module Crypto.IES is used and the
implementation generates short exponents as optimisation.
Unfortunately because of compatibility this means we get 3 sets of APIs with some redundancy:
- Crypto.DH is used when groups are custom
- Crypto.IES has new compatibility functions with data types like in Crypto.DH and removal of leading zeros (TLS <= 1.2)
- Crypto.IES existing hybrid group functions are kept and extended with FFDH validation checks …
=> Negotiated FFDHE parameters

.travis.yml, debug/src/CheckCiphers.hs, debug/src/Common.hs, debug/src/HexDump.hs, debug/src/Imports.hs, debug/src/RetrieveCertificate.hs, debug/src/SimpleClient.hs, debug/src/SimpleServer.hs, debug/src/Stunnel.hs, debug/tls-debug.cabal, session/ChangeLog.md, session/LICENSE, session/Network/TLS/Imports.hs, session/Network/TLS/SessionManager.hs, session/Setup.hs, session/session/Network/TLS/Imports.hs, session/tls-session-manager.cabal, stack.yaml
This patches do:
- warnings are disappeared thanks to a big imports.
- `tls-simpleserver` loops. So, `--session` was deleted. `tls-session-manager` is used as a session manager.
- `getAddrInfo` is used for modern style.
=> Impoving tls-debug

core/Network/TLS/Backend.hs, core/Network/TLS/Cipher.hs, core/Network/TLS/Compression.hs, core/Network/TLS/Context.hs, core/Network/TLS/Context/Internal.hs, core/Network/TLS/Core.hs, core/Network/TLS/Credentials.hs, core/Network/TLS/Crypto.hs, core/Network/TLS/Extension.hs, core/Network/TLS/Extra/Cipher.hs, core/Network/TLS/Handshake.hs, core/Network/TLS/Handshake/Client.hs, core/Network/TLS/Handshake/Common.hs, core/Network/TLS/Handshake/Server.hs, core/Network/TLS/Handshake/Signature.hs, core/Network/TLS/Handshake/State.hs, core/Network/TLS/Hooks.hs, core/Network/TLS/IO.hs, core/Network/TLS/Packet.hs, core/Network/TLS/Parameters.hs, core/Network/TLS/Receiving.hs, core/Network/TLS/Record/Disengage.hs, core/Network/TLS/Sending.hs, core/Network/TLS/State.hs, core/Network/TLS/Struct.hs, core/Network/TLS/Wire.hs, core/Network/TLS/X509.hs
This PR accepts reasonable hlint suggestions.
=> Hlint suggestions

core/Network/TLS/Core.hs
This fixes #261.
```
debug: << Alert [(AlertLevel_Warning,CloseNotify)]
debug: >> Alert [(AlertLevel_Warning,CloseNotify)]
```
=> checking EOF in bye (#261).

core/Network/TLS/Parameters.hs
Many implementations have this so I think we can enable it.
=> Enable X25519 in default parameters

core/Tests/Ciphers.hs
It looks the length is not correct in tests related to AES GCM ciphers.
Found this when testing addition of AES CCM with implementation from @wangbj.
=> IV length for AEAD ciphers

core/Network/TLS/Credentials.hs, core/Network/TLS/Imports.hs, test-scripts/TestClient.hs
Not all dependencies are ready yet but we should have compatibility with GHC 8.4 before any new release of `tls`.
=>  Compatibility with Semigroup/Monoid proposal

core/Network/TLS/Handshake/Certificate.hs, core/Network/TLS/Handshake/Client.hs, core/Network/TLS/Handshake/Server.hs, core/Network/TLS/Parameters.hs, core/Tests/Certificate.hs, core/Tests/Connection.hs, core/Tests/Tests.hs
This is to address one issue reported in #155:
```
FAIL certificate has invalid key usage for HTTPS connection [reject bad-key-usage.badtls.io:11005]
output: 200 OK
```
=> Verify certificate key usage

core/Network/TLS/Extension.hs, core/Network/TLS/Handshake/Client.hs, core/Network/TLS/Handshake/Server.hs, core/Network/TLS/Packet.hs, core/Network/TLS/Wire.hs
RFC 8446 for TLS 1.3 is coming.  My implementation of TLS 1.3 shows good inter-operability with other implementations (#167). So, I would like to start merge it into `master` step by step.
=> Extensions for TLS 1.3

core/Network/TLS/Credentials.hs, core/Network/TLS/Handshake/Process.hs, core/Network/TLS/Handshake/Server.hs, core/Network/TLS/Handshake/Signature.hs, core/Network/TLS/Handshake/State.hs, core/Network/TLS/Struct.hs, core/Tests/Connection.hs
TLS 1.3 changes some technical terms.
This PR catches up it.
Also, this PR adds new alerts.
=> Renaming for TLS 1.3

core/Benchmarks/Benchmarks.hs, core/Tests/Connection.hs, core/Tests/Tests.hs, core/tls.cabal
As mentioned previously, using async we can make sure exceptions in tlsClient/tlsServer are rethrown to the main thread. Failures interrupt the timeout and test results are reported faster.
I also increase the timeout to 1 min, hoping to resolve #252 and #281.
=> Use async in test suite

core/Network/TLS/Handshake/Client.hs, core/Network/TLS/Handshake/Random.hs, core/Network/TLS/Handshake/Server.hs, core/Network/TLS/Packet13.hs, core/Network/TLS/Parameters.hs, core/Network/TLS/Struct.hs, core/Tests/Tests.hs, core/tls.cabal
This implements downgrade protection defined in TLS 1.3.
=> Downgrade protection

core/Network/TLS/Handshake/Client.hs, core/Network/TLS/Handshake/Process.hs, core/Network/TLS/Handshake/Server.hs, core/Network/TLS/Handshake/State.hs, core/Network/TLS/Handshake/State13.hs, core/Network/TLS/Sending13.hs
Currently resumption fails with error `PSK binder validation failed` when PSK is combined with HRR.
A simple scenario to show this is to launch a server with:
```
tls-simpleserver --key test-certs/server.rsa.key --certificate test-certs/server.rsa.crt --tls13 --group p384 4433
```
and to try to resume a session like this:
```
$ openssl s_client -sess_out /tmp/session.dat
$ openssl s_client -sess_in /tmp/session.dat
```
The reason is that the "message hash" wrapping is applied only when the transcript is used for key schedule but not when computing PSK binders. This PR changes the implementation to perform the "message hash" substitution directly in the pending transcript as soon as HRR is sent/received.
With something like this, the scenario above succeeds.  And it also becomes possible …
=> Fix PSK binder with HRR

core/Network/TLS.hs, core/Network/TLS/Core.hs, core/Network/TLS/State.hs, core/Tests/Tests.hs, debug/src/SimpleClient.hs
=> One way key update

core/Network/TLS/Handshake/Client.hs, core/Network/TLS/Handshake/Server.hs, core/Tests/Tests.hs
I don't see any reason why this transition is not enabled in the server.
In the client, the scenario just needs to use the full list of supported groups. Currently it is unnecessarily restricted.
Additionally, I change comparison of PSK binders to constant time `bytesEq`, otherwise I think it completely defeats the purpose.
=> PSK fallback to full or HRR handshake

core/Network/TLS/Core.hs, core/Network/TLS/Handshake/Common13.hs, core/Network/TLS/Handshake/Server.hs, core/Network/TLS/Types.hs
A server sends only one NST after receiving client finished. This fixes the issue of `IORef` and old RTT but gives up interoperability somewhat. This pach is consistent with client authentication since transcript hash is calculated in the finish action.
=> sending a new session ticket after client finished

core/Network/TLS/Context/Internal.hs, core/Network/TLS/Core.hs, core/Network/TLS/Handshake/Server.hs, core/Network/TLS/Handshake/State13.hs
Pending actions are now able to verify what message type is received before executing the action.
=> Improve pending-action mechanism

core/Benchmarks/Benchmarks.hs, core/tls.cabal
This removes many dependencies.
Before:
```
$ stack ls dependencies --test --bench | wc -l
94
```
After:
```
$ stack ls dependencies --test --bench | wc -l
60
```
=> Use gauge instead of criterion

core/Network/TLS/Core.hs, core/Network/TLS/Handshake/Client.hs, core/Network/TLS/Handshake/Server.hs, core/Network/TLS/Util.hs, core/Tests/Tests.hs
This splits 0-RTT data in 16384-byte chunks like regular data.
Additionally the PR fixes server-side handling of early-data overflow:
- alert was not sent to the client
- overflow check must be based on the total size received, not the individual segments
=> Early data over 16384 bytes

.hlint.yaml, core/Network/TLS/Context.hs, core/Network/TLS/Context/Internal.hs, core/Network/TLS/Core.hs, core/Network/TLS/Handshake.hs, core/Network/TLS/Handshake/State13.hs, core/Tests/Tests.hs
Completes the use of read lock / write lock to handle concurrent calls sending and receiving data.
Hopefully it will be enough to solve the issue raised in #323.
=> Some thread-safety for writes

core/Network/TLS/Handshake/Client.hs, core/Network/TLS/Handshake/Random.hs
Some TLS 1.3 servers return a TLS 1.2 downgrade sentinel in the
server hello along with TLS 1.3 in the supported_versions extension
and TLS 1.2 in the ServerHello legacy version.
When we would actually select 1.3, it is wrong to trigger downgrade
detection based solely on the server random.
=> Avoid downgrade detection false-positive

core/Network/TLS/Context/Internal.hs, core/Network/TLS/Core.hs, core/Network/TLS/Handshake/Client.hs, core/Network/TLS/Handshake/Common13.hs, core/Network/TLS/Handshake/Key.hs, core/Network/TLS/Handshake/Server.hs, core/Network/TLS/Handshake/Signature.hs, core/Tests/Connection.hs, core/Tests/Tests.hs
Passing test cases of client auth and usage.
Interoperability with OpenSSL is confirmed:
```
% stack exec tls-simpleserver -- -v --key=$SOMEWHERE/serverkey.pem --certificate=$SOMEWHERE/servercert.pem 13443 --tls13 --trust-anchor=$SOMEWHERE/cacert.pem
```
NG:
```
% ./opensslwrap.sh s_client 127.0.0.1:13443
OK:
```
% ./opensslwrap.sh s_client -cert=$SOMEWHERE/clientcert.pem -key=$SOMEWHERE/clientkey.pem 127.0.0.1:13443
```
=> Client auth server side

core/Benchmarks/Benchmarks.hs, core/Network/TLS/Core.hs, core/Network/TLS/Extension.hs, core/Tests/Connection.hs, core/Tests/Tests.hs, debug/src/SimpleClient.hs, debug/src/Stunnel.hs, debug/tls-debug.cabal
Improves the implementation of `sessionResumeOnlyOnce` to get the "only once" constraint.
Regarding connection termination, I realized that the correct pattern is actually to call `recvData` _after_ `bye`. Because this sequence will not deadlock when facing a peer doing exactly the same thing. The pattern is captured in a test utility and called every time the connection is terminated without calling `recvData`.
=> Improvements to tests and tools

core/Network/TLS/Core.hs, core/Network/TLS/Handshake/Client.hs, core/Network/TLS/Handshake/Common13.hs, core/Network/TLS/Handshake/Server.hs, core/Network/TLS/Packet13.hs, core/Network/TLS/Parameters.hs
- Prevent negotation of non-"null" compression
- Test that NewSessionTicket13 is received by a client, not a server
=> Two simple checks for TLS13

core/Network/TLS.hs, core/Network/TLS/Context.hs, core/Network/TLS/Context/Internal.hs, core/Network/TLS/Core.hs, core/Network/TLS/Extension.hs, core/Network/TLS/Handshake/Client.hs, core/Network/TLS/Handshake/Server.hs, core/Network/TLS/Parameters.hs, core/Network/TLS/State.hs, core/Network/TLS/Types.hs
This PR exposes necessary types (no haddock warnings anymore), updates document and fixes coding style.
=> Minor fixes

core/Network/TLS/Handshake/Common.hs
Function recvClientData did not accept a client flight with messages
ClientKeyXchg and CertVerify received from the same Handshake packet.
This patch extends the state machine to transform remaining handshake
messages as input to RecvStateNext.
Resolves #350.
=> Fix recvClientData with single Handshake packet

core/Network/TLS.hs, core/Network/TLS/Context.hs, core/Network/TLS/Context/Internal.hs, core/Network/TLS/Core.hs, core/Network/TLS/Extension.hs, core/Network/TLS/Handshake.hs, core/Network/TLS/Handshake/Client.hs, core/Network/TLS/Handshake/Common.hs, core/Network/TLS/Handshake/Server.hs, core/Network/TLS/Handshake/State.hs, core/Network/TLS/PostHandshake.hs, core/Network/TLS/Sending13.hs, core/Network/TLS/State.hs, core/Network/TLS/Struct13.hs, core/Network/TLS/Types.hs, core/Network/TLS/Util.hs, core/Tests/Tests.hs, core/tls.cabal, debug/src/Common.hs
Adds basic client/server support for PHA.
Primary goal is to have client support for scenarios where this is needed by the server. The extension is sent unconditionnally since it is not any different than a renegotiation handshake before TLS13, which is always possible. Existing configuration and hooks about client authentication will apply, so this should minimize impact of enabling TLS13.
Ability for a server to request authentication is also added, with design similar to key update. i.e. the API does _nothing_ before TLS13, and does not try to trigger a renegotiation instead.
Internally the existing client-certificate code is reused, with handshake state being reverted at specific locations. The reasons for reverts are:
- successive post-handshake authentications don't cumulate in the …
=> Post-handshake authentication

core/Network/TLS/Core.hs, core/Network/TLS/Handshake/Common.hs, session/ChangeLog.md, session/Network/TLS/SessionManager.hs, session/tls-session-manager.cabal
@ocheron found that session values of `ByteString` lead memory leak. I also found that session keys (IDs) of `ByteString` leak memory. 1afb213 fixes it. In my server, this reduced memory usage from 30% to 11%.
b0ba6a9 changes the internal data structure from `ByteString` to `ShortByteString` to avoid fragmentation. This improves memory footprint from 11% to 5%. I did both experiments with `dbMaxSize` = 1,000.
=> Fixing memory leak

core/Network/TLS/Handshake/Client.hs
The condition with isAgeValid was used for extension "pre_shared_key"
but not when determining whether to send 0-RTT data or not.  With an
expired ticket adjustExtentions was called and modified an extension
which was not "pre_shared_key".
This commit rearranges the variables so that the result of isAgeValid
is used at all necessary places.
=> Don't send 0-RTT data when ticket is expired

core/Network/TLS/Handshake/Client.hs, core/Network/TLS/Handshake/Server.hs
Makes client extension "psk_key_exchange_modes" mandatory for PSK handshake, and verifies adequacy of server-selected cipher.
Sending NST when PSK_DHE_KE is not supported is not useful, the implementation is not able to resume with PSK_KE.
=> Verification of PSK modes

core/Network/TLS/Context/Internal.hs, core/Network/TLS/Core.hs, core/Network/TLS/Handshake/Client.hs, core/Network/TLS/Handshake/Common.hs, core/Network/TLS/Handshake/Server.hs, core/Network/TLS/IO.hs
Each time the Rx key is modified with `setRxState` we can verify that there is no message deprotected with the previous key still unconsumed. This includes verifying the tail of a received `[Handshake13]` packet as well as incomplete handshake fragments stored in the context.
=> Check record alignment when changing Rx key

core/Network/TLS/Handshake/Client.hs
Having a dedicated error in case of deployment issue will allow to understand the cause more easily, i.e. without requiring to capture server hello.
=> Abort 0-RTT connection without TLS13

core/Network/TLS/Crypto.hs, core/Network/TLS/Crypto/Types.hs, core/Network/TLS/Handshake/Client.hs, core/Network/TLS/Handshake/Common.hs, core/Network/TLS/Handshake/Common13.hs, core/Network/TLS/Handshake/Key.hs, core/Network/TLS/Handshake/Server.hs, core/Network/TLS/Handshake/Signature.hs, core/Network/TLS/X509.hs
1024-bit is a small RSA size but this is often the default value when generating with some tools.
As reported in #365, enabling RSA-PSS signatures has side effect and prevents to use keys which were accepted before.
This PR extends selection of hash algorithm to avoid the fatal failure with SHA-512, and pick SHA-384 (or lower) instead.
The data type `DigitalSignatureAlg` is removed, instead `signatureCompatible` and calling functions use `PubKey` instead. When deciding about signature schemes, the full content of the public key is available, so the size of the modulus can be checked.
`PubKey` allows more key types than `DigitalSignatureAlg`, so to prevent an invalid input to a function like `signatureParams`, the existing decoding to `DigitalSignatureAlg` that previously rejected bad …
=> Avoid handshake failure with small RSA keys

core/Network/TLS/Struct.hs
I don't know `Network.TLS.Struct` is a right place to implement this but I want this feature to make debugging easier.
=> making extensions readable.

core/Network/TLS/Context/Internal.hs, core/Network/TLS/Handshake/Process.hs, core/Network/TLS/IO.hs, core/Network/TLS/Packet.hs, core/Network/TLS/Receiving.hs, core/Network/TLS/Receiving13.hs, core/Network/TLS/Sending.hs, core/Network/TLS/Sending13.hs
This patches make `Sending` and `Receiving` symmetric as described in #392.
Also, these reduce unnecessary encodings to calculate transcript hash.
=> refactoring for sending and receiving

core/Network/TLS/Handshake/Server.hs, core/Tests/Tests.hs
When TLS13 is negotiated, the callback `onServerNameIndication` in called too early in the server code flow. In case of HelloRetryRequest there is an unnecessary call for the first Client Hello. It is needed only for the second Client Hello.
To avoid this, the PR moves the call to splitted implementations TLS12/TLS13:
- Knowning what credentials are available is required for cipher selection < TLS13
- With TLS13, `onServerNameIndication` can be called after HRR handling
Test case "SNI" is also extended to verify that `onServerNameIndication` is called once, and that `getClientSNI` returns a correct result on client side.
=> Avoid calling onServerNameIndication twice with HRR

core/Network/TLS.hs
To make the document more readable, sections and subsections are re-ordred.
Q1) Many things in "Raw types" are not used. Is it necessary to export them from the top module? Should be create the `Internal` module to export them?
Q2) Why are `ValidationChecks` and `ValidationHooks` exported?
Q3) Why aren't necessary things such as `ciphersuite_strong` exported?
=> docment ordering

README.md, core/Network/TLS.hs, core/Network/TLS/Context/Internal.hs, core/Network/TLS/Extension.hs, core/Network/TLS/Handshake/Client.hs, core/Network/TLS/Handshake/Common.hs, core/Network/TLS/Handshake/Common13.hs, core/Network/TLS/Handshake/Process.hs, core/Network/TLS/Handshake/Server.hs, core/Network/TLS/Handshake/State.hs, core/Network/TLS/Packet.hs, core/Network/TLS/Parameters.hs, core/Network/TLS/Types.hs, core/Tests/Connection.hs, core/Tests/Tests.hs, core/tls.cabal, debug/src/Common.hs, debug/tls-debug.cabal, session/Network/TLS/SessionManager.hs
Adds [RFC 7627](https://tools.ietf.org/html/rfc7627), which is a prerequisite for EKM and Token Binding before TLS 1.3.
For this I add an extensible list of flags to SessionData.  Encrypted SNI would benefit from this too.  It modifies the API but I think we should try this change in a minor version (not sure many people really depend on SessionData, but what is clear is that major versions tend to be blocked for months in stackage).
=> Extended Master Secret

core/Network/TLS.hs
Cc: @eyeinsky
This should fix #405
=> exposing getClientCertificateChain.

core/Network/TLS/Record/Disengage.hs, core/Network/TLS/Struct.hs
Contrary to TLS, SSL requires the CBC padding to be minimal, i.e. the minimum number of bytes to get a multiple of the block size.  This PR adds the verification and makes tlsfuzzer script
`test-SSLv3-padding.py` all successful.
=> Check SSLv3 padding length

core/Network/TLS/Handshake/Server.hs, core/Tests/Tests.hs
ALPN should be decided before the decision of 0-RTT.
The first commit discloses the bug and the second one should fix it.
@ocheron BTW, do you know which specification requires the rule implemented in `checkSessionEquality`? I would like to add comments there.
=> Fixing ALPN

core/Network/TLS/Crypto.hs, core/Network/TLS/Handshake/Client.hs, core/Network/TLS/Handshake/Common13.hs, core/Network/TLS/Handshake/Key.hs, core/Network/TLS/Handshake/Server.hs, core/Network/TLS/Handshake/Signature.hs, core/Network/TLS/Parameters.hs, core/Tests/Connection.hs
* Prevents to use EdDSA with TLS10 and TLS11. EdDSA support is signaled through "signature_algorithms" only, so needs TLS12 or later for proper negotiation between client and server.
* For TLS13, verifies that the received elliptic curve matches the hash algorithm chosen by peer (i.e. SHA-256 is for P-256, SHA-384 is for P-384, etc.)
* For TLS12 or before, verifies that the elliptic curve used to generate an ECDSA signature matches sent extension "Supported Elliptic Curves"
* For uniform behavior, make sure we call isDigitalSignaturePair before TLS12 too
=> Additional verification regarding EC signatures

core/Benchmarks/Benchmarks.hs, core/Tests/Connection.hs, core/Tests/Tests.hs
Minor test cleanups for #413 and #286.
CC @ocheron
=> Test cleanups for timeout and async usage

core/Network/TLS/Handshake/Client.hs
Some releases of J2SE 6 don't like receiving ClientHello with
zero-length extension at last position and abort the handshake with
"unexpected_message" alert.
To avoid this, the commit moves one TLS13 extension in the list sent
by a client.
=> Restore interoperability with early Java 6

core/Network/TLS/Context.hs, core/Network/TLS/Context/Internal.hs, core/Network/TLS/Core.hs, core/Network/TLS/Credentials.hs, core/Network/TLS/Handshake/Client.hs, core/Network/TLS/IO.hs, core/Network/TLS/Imports.hs, core/Network/TLS/Sending.hs, core/Network/TLS/Sending13.hs, core/Network/TLS/Util.hs
Replaces the constant 16384 used at multiple places with a runtime variable held by the context.
A `Nothing` value can be used to disable fragmentation (assuming an alternative record layer is able to deal with this). The variable could be changed to IORef later, to implement extension "max_fragment_length".
The PR also includes some code clean-up, mostly related to CPP.
=> Maximum fragment size

core/Network/TLS/Context.hs, core/Network/TLS/Context/Internal.hs, core/Network/TLS/Core.hs, core/Network/TLS/Extension.hs, core/Network/TLS/Handshake/Client.hs, core/Network/TLS/Handshake/Common.hs, core/Network/TLS/Handshake/Common13.hs, core/Network/TLS/Handshake/Control.hs, core/Network/TLS/Handshake/QUIC.hs, core/Network/TLS/Handshake/Server.hs, core/Network/TLS/Handshake/State.hs, core/Network/TLS/Handshake/State13.hs, core/Network/TLS/IO.hs, core/Network/TLS/Parameters.hs, core/Network/TLS/QUIC.hs, core/Network/TLS/Record/Layer.hs, core/Network/TLS/Record/State.hs, core/Network/TLS/Sending.hs, core/Network/TLS/Sending13.hs, core/Network/TLS/Types.hs, core/tls.cabal
As discussed in #392, I have implemented QUIC APIs based on threads. This does not change `Client.hs` and `Server.hs` a lot. QUIC APIs are provided in `Network.TLS.QUIC`. So, `Network.TLS` remains the same.
I joined 16th QUIC interop and am now confident the quality of this code: https://docs.google.com/spreadsheets/d/1D0tW89vOoaScs3IY9RGC0UesWGAwE6xyLk0l4JtvTVg
@ocheron I don't expect that this PR will be merged quickly. But I would like to get feedback if any.
=> Handshake controller for QUIC

core/Network/TLS/Core.hs, core/Network/TLS/Handshake/Client.hs, core/Network/TLS/Handshake/Control.hs, core/Network/TLS/Handshake/Server.hs, core/Network/TLS/Parameters.hs, core/Network/TLS/QUIC.hs
The old implementation of QUIC early data is just specifying wire data (`ByteString`) to the configuration. This is good for HTTP/1.1 whose protocol is based on text. But for HTTP/3, it's hard to generate early data in advance since multiple threads generate frames.
The current implementation of QUIC early data is just specifying `Bool` (use0RTT) to the configuration. If `True`, the client controller MUST return after sending Client Hello so that QUIC applications can send streams and internal code encrypted them with client early secret.
If `False`, the client controller MUST return after sending Client Finished. Unfortunately, the old two-phase approach cannot implements this two modes.
This PR removes the controls and the exported states. The *handshakers* purely synchronize with QUIC …
=> Stateless handshaker

core/Network/TLS/Context.hs, core/Network/TLS/Context/Internal.hs, core/Network/TLS/Handshake/Client.hs, core/Network/TLS/Handshake/Control.hs, core/Network/TLS/Handshake/Server.hs, core/Network/TLS/QUIC.hs
This is an alternative to #432. `Context` is passed to `sync` from client and server. `RTT0Status` is not exported since `Information` has `infoIsEarlyDataAccepted`.
=> Setting necessary QUIC parameters before 1RTT gets ready (2)

core/Network/TLS/Extra/Cipher.hs, core/tls.cabal, debug/src/Common.hs, debug/tls-debug.cabal
Uses runtime flags provided by cryptonite to define AEAD cipher preference based on hardware-acceleration support.
The main lists of ciphersuites `_default`, `_all` and `_strong` are modified, most application code will directly get this.
A version of those lists without dynamic ordering is provided in case application code needs it.
This gives almost identical order to what was there previously, except the position of CCM ciphers is slightly ajusted.
Debug tools are extended to show the optimizations that are active.
Closes #369.
=> Sort ciphersuites based on hardware-acceleration support

core/Network/TLS.hs, core/Network/TLS/Context.hs, core/Network/TLS/Context/Internal.hs, core/Network/TLS/Handshake/Client.hs, core/Network/TLS/Handshake/Common.hs, core/Network/TLS/Handshake/Common13.hs, core/Network/TLS/Handshake/Process.hs, core/Network/TLS/Handshake/Server.hs, core/Tests/Tests.hs
@kazu-yamamoto this is partially done.
I tried putting Finished into HandshakeState but it has Show instance (although I didn't check if it's actually needed, but it would be a breaking change to remove it), and IORef does not.
Currently, I think, it stores Finished of the current peer for both Client and Server, and stores client's Finished in the server only.
I could not find the place in the client where server's Finished is validated - does client do it at all? If not, should it be added?
Also, re FinishedData vs wire-bytes, FinishedData is the same as ByteString - is it not wire-bytes?
=> add getFinished and getPeerFinished functions for Context, closes #442

core/Network/TLS/Core.hs, core/Network/TLS/ErrT.hs, core/Network/TLS/Handshake/Certificate.hs, core/Network/TLS/Handshake/State.hs, core/Network/TLS/Record/State.hs, core/Network/TLS/State.hs, core/Network/TLS/Struct.hs, core/tls.cabal
Depends on haskell-tls/hs-certificate/pull/130
Tested with 
cabal test --constraint='mtl<2.2.2' all -w ghc-8.6.5
and 
cabal test --constraint='mtl>=2.3' all -w ghc-9.2.2
=> Require mtl-2.2.1 or newer

core/CHANGELOG.md, core/Network/TLS/Core.hs, core/Network/TLS/Handshake/Certificate.hs, core/Network/TLS/Handshake/Client.hs, core/Network/TLS/Handshake/Common.hs, core/Network/TLS/Handshake/Common13.hs, core/Network/TLS/Handshake/Key.hs, core/Network/TLS/Handshake/Process.hs, core/Network/TLS/Handshake/Server.hs, core/Network/TLS/Handshake/Signature.hs, core/Network/TLS/Handshake/State13.hs, core/Network/TLS/IO.hs, core/Network/TLS/QUIC.hs, core/Network/TLS/Record/Disengage.hs, core/Network/TLS/Record/Reading.hs, core/Network/TLS/Struct.hs
I was writing automated tests for some error handling cases in library that uses `Network.TLS` and found it unclear what all of the fields in this tuple (especially the `Bool`) meant.  Here's an attempt at describing them.
=> Describe the elements of Error_Protocol's three-tuple

tls/Network/TLS/Extra/Cipher.hs, tls/Network/TLS/Parameters.hs, tls/util/tls-client.hs, tls/util/tls-server.hs
- setting supportedCiphers to ciphersuite_default
- ciphersuite_default is now the same as ciphersuite_strong
See https://github.com/kazu-yamamoto/crypton-connection/pull/3
=> Importing Extra.Cipher is not necessary anymore

tls/Network/TLS/Context/Internal.hs, tls/Network/TLS/Handshake/Client.hs, tls/Network/TLS/Handshake/Client/TLS12.hs, tls/Network/TLS/Handshake/Client/TLS13.hs, tls/Network/TLS/Parameters.hs, tls/util/tls-client.hs
To obtain a handshake mode, `contextGetInformation` cab be used if `Context` is available.
But `Context` is not always available.
A good example is `http2-tls`.
So, this patch add a hook called `onServerFinished` which enables to get `Information` for clients when its connection is established.
=> defining onServerFinished

tls-session-manager/tls-session-manager.cabal, tls/Network/TLS/Context.hs, tls/Network/TLS/Context/Internal.hs, tls/Network/TLS/Core.hs, tls/Network/TLS/Handshake/Client.hs, tls/Network/TLS/Handshake/Client/ClientHello.hs, tls/Network/TLS/Handshake/Client/Common.hs, tls/Network/TLS/Handshake/Client/ServerHello.hs, tls/Network/TLS/Handshake/Client/TLS12.hs, tls/Network/TLS/Handshake/Common.hs, tls/Network/TLS/Handshake/Common13.hs, tls/Network/TLS/Handshake/Server.hs, tls/Network/TLS/Handshake/Server/ServerHello12.hs, tls/Network/TLS/Handshake/Server/ServerHello13.hs, tls/Network/TLS/Handshake/Server/TLS12.hs, tls/Network/TLS/Handshake/State.hs, tls/Network/TLS/Parameters.hs, tls/Network/TLS/Session.hs, tls/Network/TLS/State.hs, tls/tls.cabal, tls/util/Client.hs, tls/util/tls-client.hs, tls/util/tls-server.hs
1.1.1.1 and 8.8.8.8 provide multiple NewSessionTickets.
To resume a session, clients need to specify multiple tickets.
Since these tickets are obtained in the previous session, `SessionData` is unique.
So, binders for tickets are identical.
=> Multiple PSKs

tls/Network/TLS/Core.hs
8.8.8.8 sends NST just after EE and SF.
So, "hs" is not null.
=> checkAlignment only checks isRecvComplete

tls/CHANGELOG.md
See:
* #482 
The motivation for this pull request is that the Haskell 2010 Language Report is slient-ish on the ability to update values with record syntax when the data constructor is not exported but the field name is exported. See https://discourse.haskell.org/t/updating-values-with-record-syntax-when-data-constructor-is-not-exported/10603/8
=> Fix #482 Elaborate change log entry for tls-2.1.0

tls/Network/TLS.hs, tls/Network/TLS/Hooks.hs, tls/Network/TLS/Parameters.hs, tls/Network/TLS/QUIC.hs
@MaxGabriel This tries taking over #487.
I would like to export all default values.
This breaks the `quic` package but it can be fixed easily.
=> exporting defaults

tls/Network/TLS/Extra/Cipher.hs
With all the DHE RSA ciphers gone, it was no longer possible to make SMTP STARTTLS connections to a server wtih RSA certs and no ECDHE support, just FFDHE4096 available.  This sort of thing may be rare on the web, but is not nearly as rare in other application use cases.
This PR, just adds back the ciphers, without adding them to the default set, the application stil has to explicitly choose to include `ciphersuite_dhe_rsa` in the mix (which I did in the DANE scanner).
If you'd prefer to not expose the list directly, and rather just include these in the default list, then tests would have to also change to enable DHE in supported groups when these ciphers are chosen...
=> Restore a few DHE_RSA ciphers
