haskell-tls/hs-tls

- core/Network/TLS/Backend.hs
- core/tls.cabal
https://ghc.haskell.org/trac/ghc/ticket/5797
> Add workaround to hang in recv on Windows related to

- core/Network/TLS/Handshake/Server.hs
I'm sending a PR just in case. If I should push this kind of commit directly, please tell me.
> using a symbol instead of a value for secure renego.

- core/Network/TLS/Handshake/Server.hs
RFC 6066:
A server that receives a client hello containing the "server_name"
extension MAY use the information contained in the extension to guide
its selection of an appropriate certificate to return to the client,
and/or other aspects of security policy. In this event, the server
SHALL include an extension of type "server_name" in the (extended)
server hello. The "extension_data" field of this extension SHALL be
empty.
> sending an empty server name from a server if necessary. (#175)

- CONTRIBUTING.md
I've made a small guide to make sure we agree on how to maintain tls, and that we don't step on each other toes. @kazu-yamamoto @vdukhovni @ocheron please review and propose improvements/etc..
> add CONTRIBUTING

- core/Network/TLS/Handshake/Client.hs
I think this case is not necessary.
> removing a redundant case

- core/Network/TLS/Credentials.hs
- core/Network/TLS/Handshake/Server.hs
> Minor fixes

- core/CHANGELOG.md
> updating changelog.

- core/CHANGELOG.md
- core/Network/TLS/Crypto/IES.hs
- core/Network/TLS/Handshake/Client.hs
- core/Network/TLS/Handshake/Key.hs
- core/tls.cabal
- debug/tls-debug.cabal
- test-scripts/tls-test.cabal
Will provide better validation we wanted:
- haskell-crypto/cryptonite#165
- haskell-crypto/cryptonite#178
> Using cryptonite-0.24

- core/Tests/Certificate.hs
- core/tls.cabal
> Using x509 1.7

- .travis.yml
> Use cabal-2.0 for 8.2.1

- core/Network/TLS/Extension.hs
Let's use newtype for a single constructor.
> using newtype instead of data.

- debug/src/RetrieveCertificate.hs
- debug/src/Stunnel.hs
`Network.BSD` will be obsolete. Let's use the modern API.
> using getAddrInfo.

- stack.yaml
> fixing stack.yaml.

- core/Benchmarks/Benchmarks.hs
- core/Tests/Connection.hs
- core/Tests/Tests.hs
Improves the testing infrastructure to reveal an issue in some test cases and applies a workaround.
See commit messages for details.
> Fix resumption test cases

- core/Tests/Tests.hs
This makes it easier to implement should-fail test cases.
> returning debug information from runTLSInitFailure.

- core/Network/TLS/Core.hs
- core/Network/TLS/Extension.hs
- core/Network/TLS/Handshake/Client.hs
- core/Network/TLS/Handshake/Common.hs
- core/Network/TLS/Handshake/Common13.hs
- core/Network/TLS/Handshake/State.hs
- core/Network/TLS/Handshake/State13.hs
- core/Network/TLS/Packet13.hs
This should fix #255, #304 and #305.
> Refactoring

- core/Network/TLS/Backend.hs
- core/Network/TLS/Handshake/Client.hs
- core/Network/TLS/Handshake/Server.hs
- core/Network/TLS/IO.hs
- core/Network/TLS/Packet.hs
Changing styles suggested by hlint.
> Style only

- core/Network/TLS.hs
- core/Network/TLS/Parameters.hs
This PR makes the doc readable.
> Updating doc

- core/Network/TLS/Extension.hs
- core/Network/TLS/Handshake/Key.hs
- core/Network/TLS/IO.hs
- core/Network/TLS/Imports.hs
- core/Network/TLS/Packet.hs
- core/tls.cabal
For a new release we should have something like this so there is no compilation error with GHC 8.8.1 when out.
> Compatibility with base-4.13.0.0

- core/Network/TLS/Packet.hs
- core/Network/TLS/Packet13.hs
- core/Tests/Marshalling.hs
> CH and SH in encodeHandshake13' and decodeHandshake13'.

- core/Network/TLS/Core.hs
- core/Network/TLS/Handshake/Client.hs
- core/Network/TLS/Handshake/Common13.hs
- core/Network/TLS/Handshake/Key.hs
- core/Network/TLS/Handshake/Process.hs
- core/Network/TLS/Handshake/Server.hs
- core/Network/TLS/Handshake/State.hs
- core/Network/TLS/Types.hs
This is the second step in #139.
> Adding new types for secrets for refactoring

- core/Network/TLS/Handshake/Client.hs
- core/Network/TLS/Packet.hs
- core/Network/TLS/Util/Serialization.hs
Simple modifications to remove a few warnings in the weeder build.
> Avoid 3 weeder warnings

- core/Network/TLS/Handshake/Server.hs
- core/Network/TLS/Parameters.hs
> Sending no_application_protocol

- core/Network/TLS/QUIC.hs
With this patch, quic/tls passes the test of `h3spec`.
> sending MissingExtension if QUIC TPs are missing.

- core/Network/TLS/Handshake/Server.hs
- core/Network/TLS/Parameters.hs
> Implementation for dynamically setting enctypted extensions

- tls/Network/TLS.hs
- tls/Network/TLS/Parameters.hs
@khibino This should fix #498.
> defining defaultKeyLogger with SSLKEYLOGFILE

- tls/util/tls-client.hs
> add --trusted-anchor cli option to tls-client
